Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'lib/templates/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

# Don't worry about documentation for now.
# In particular, this fails for things like
# controller files, which seems unnecessary.
Style/Documentation:
  Enabled: false
 
# Relax complexity testing to codeclimate standards (roughly).
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 160
Style/PredicateName:
  Enabled: false
